name: Latest Velog Posts

on:
  schedule:
    # ë§¤ì¼ ìì •(UTC ê¸°ì¤€)ì— ìë™ìœ¼ë¡œ ì‹¤í–‰ë˜ë„ë¡ ì„¤ì •
    - cron: '0 0 * * *'
  workflow_dispatch: # ìˆ˜ë™ìœ¼ë¡œ ì—…ë°ì´íŠ¸ ë²„íŠ¼ì„ ëˆ„ë¥¼ ìˆ˜ ìˆê²Œ í•´ì£¼ëŠ” ì˜µì…˜

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in velog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          # ğŸ‘‡ ì•„ë˜ ì£¼ì†Œì˜ 'ë³¸ì¸ì•„ì´ë””' ë¶€ë¶„ì„ ì‹¤ì œ ë„¤ ë²¨ë¡œê·¸ ì•„ì´ë””ë¡œ ê¼­ ë°”ê¿”ì¤˜! (@ ê¸°í˜¸ëŠ” ëƒ…ë‘¬ì•¼ ë¨)
          feed_list: "https://v2.velog.io/rss/@halfgene"
